TestProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('testques.urls')),
    
]

testques/urls.py
from django.urls import path
from . import views

"""
url defination file for test app /test/<---->/
"""

urlpatterns=[
	path('', views.index, name="index"),
	path('<int:test_id>/', views.detail, name="detail"),
]

testques/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	"""
	Model for saving Questions in database
	"""
	question_text = models.CharField(max_length=300)
	

	def __str__(self):
		"""
		String representation of the object
		"""
		return self.question_text


class Option(models.Model):
	"""
	Option model for question having a OneToMany Relationship with 
	Question Mode
	"""
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	option_text = models.CharField(max_length=200)

	def __str__(self):
		"""
		String representation of the object
		"""
		return self.option_text



class Group(models.Model):
	"""
	Group model having multiple question to form a group
	"""
	group_name = models.CharField(max_length=100)
	question = models.ManyToManyField(Question)
	
	def __str__(self):
		"""
		String representation of the object
		"""
		return self.group_name

testques/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Group, Option
# Create your views here.


def index(request):
	"""
	index function for test/
	"""
	test_groups = Group.objects.all()
	context = {
			   'groups':test_groups
				}
	return render(request, 'index.html', context)


def detail(request, test_id):
	"""
	page for test/<test-d>
	"""

	test_group = Group.objects.get(id=test_id)
	print(type(test_group))
	# breakpoint()
	questions_qs = test_group.question.all()

	context = {'question_qs':questions_qs}

	return render(request, 'detail.html',context)

testques/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">	
		.bt-op{
			width: 50px;
			background-color: blue;

		}
	</style>

	<meta charset="utf-8">
	<title>{%  block title %} {% endblock %}</title>
</head>
<body>
{%  block body %} {% endblock %}
</body>
</html>

testques/templates/detail.html
{% extends 'base.html' %}

{%  block title %}
	Detail
	{% endblock %} 

{%  block body %} 
	<ul>
		{{group}}
	{% for question in question_qs %}
	<hr>
		<li style="list-style-type: none;">Q : {{question.question_text}}</li>
		
		<form action="#" method="POST">
			{% csrf_token %}
		<label for="op_id">Choose an option:</label>
		<select name="op_id" style="background-color: blue; margin: 30px;">
		{% for option in question.option_set.all %}
			<option class="bt-op" value="{{option.id}}">{{option.option_text}}</option>
		{% endfor %}
			
	
		</select>
		<input type="submit" name="submit" value="Submit">
	</form>
</hr>
	{% endfor %}
	</ul>
{% endblock %}

testques/templates/index.html
{% extends 'base.html' %}

{%  block title %}
	index
{% endblock %} 

{%  block body %} 
	<ul>
	{% for sub in groups %}

		<li> <a href="/test/{{sub.id}}/" >{{sub}} </a></li>
	{% endfor %}
	</ul>
{% endblock %}